bookcollection/urls.py
from django.urls import path
from bookcollection  import views

'''
make sure to check space blanks in paths path("",views...)
'''
urlpatterns =[
    path("",views.index,name='catalog'),
    path("books/",views.booklist,name='books'),
    path("book/<int:pk>/",views.bookdetails,name="book-detail"),
    path("author/",views.author,name='author'),
    path("author/<int:pk>/",views.authordetail,name='author-detail'),
    path("borrowed",views.loanbook.as_view(),name='borrowed'),
    path("allbooks",views.my_staff,name='allbooks'),
    path('book/<uuid:pk>/userrenew/',views.userrenewsystem,name='userrenewsystem'),
    path('book/<uuid:pk>/renew/',views.renewsystem,name='renew-system'),
    path('available',views.availale,name='available'),
    path('issued/<uuid:pk>/issue',views.issuesystem,name='issue'),
    

    
]   

thirdproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
# from bookcollection import urls

urlpatterns = [
    path('catalog/',include('bookcollection.urls')),
    path('admin/', admin.site.urls),
    #Add django site authentications urls(for login,logout,password management)
    path('accounts/',include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
        

bookcollection/models.py
from django.db import models
import uuid
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date       
from django.contrib.auth.models import Permission
# Create your models here.
# uuidField = uuid.UUID(str(uuidField))
class Book(models.Model):
    title=models.CharField('Title',max_length=300)
    author=models.ForeignKey('Author',on_delete=models.SET_NULL,null=True)
    summary=models.TextField(null=True,blank=True)
    genre=models.ManyToManyField('Genre',help_text='select the genre for this book')
    isbn  =models.CharField('ISBN',max_length=20,help_text='13 digit unique international code')

    def display_genre(self):
        "creating the string of genre" 
        return ','.join(genre.name for genre in self.genre.all())

    display_genre.short_description = 'Genreeee'     
    class Meta:
        ordering=['title']


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
       
        return reverse('book-detail', args=[str(self.id)])


class Genre(models.Model):
    name=models.CharField('Genre',max_length=30,help_text='enter genre like fiction,action,romantic ')

    def __str__(self):
        return self.name

class Author(models.Model):
    name=models.CharField("Name",max_length=200)
    dateofbith=models.DateField("Birth-date",null=True,blank=True)
    dateofdeath=models.DateField("Died",null=True,blank=True)
    image=models.ImageField(upload_to='images/',blank=True,null=True)

    def __str__(self):
        return self.name

    #  get_absolute-url is used for creating the url of this modelclass
    def get_absolute_url(self):
        return reverse('author-detail',args=[str(self.id)])


class Bookinstances(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,help_text='unique id for this part of the book across library')
    book1=models.ForeignKey('Book',on_delete=models.SET_NULL,null=True)
    print("sahil2121212121212")
    print(book1)
    imprint=models.CharField(max_length=300)
    due_back=models.DateField(null=True,blank=True)
    loan_status=[('m','Maintenance'),('o','onloan'),('r','reserved'),('a','available')]


    status=models.CharField(max_length=40,choices=loan_status,default='m',help_text='Book Avalilability')

    borrower=models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)

    
    class Meta:
        permissions=(("can_mark_returned","set book as returned "),("staff","for staff only"),)
        # ("can_renew","renew the book"),
        ordering=['id']

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


    
    def __str__(self):  
        print(self.id)
        return ('{0} ({1})'.format(self.id, self.book1.title))


class layout(models.Model):
    images=models.ImageField(upload_to='images/')

bookcollection/forms.py
import datetime
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from .models import Bookinstances
class renewalbookform(forms.Form):
    renew=forms.DateField(help_text='enter the date between now and the 4 weeks')
    def clean_renew(self):
        date=self.cleaned_data['renew']

        if date<datetime.date.today():
            raise ValidationError(_("Invalid date - enter the correct date "))

        elif date>datetime.timedelta(weeks=4)+datetime.date.today():
            raise ValidationError(_("Invalid date - enter the date between now and the next 4 weeks"))

        return date




class issuessystemform(forms.ModelForm):
    # user=forms.CharField(help_text='enter the name of user to be issued',widget=forms.Select(choices))
    due_date=forms.DateField(help_text='enter the date between now and the 4 weeks')
      
    class Meta:
        model=Bookinstances
        fields=['borrower'] 
    



    def clean_renew(self):
        date=self.cleaned_data['renew']
        
        if date<datetime.date.today():
            raise ValidationError(_("Invalid date - enter the correct date "))

        elif date>datetime.timedelta(weeks=4)+datetime.date.today():
            raise ValidationError(_("Invalid date - enter the date between now and the next 4 weeks"))

        return date
    






# forms validation method are run after the field name to_python and validate method
# or it can use the clean_fieldname

bookcollection/views.py
import datetime
from django.shortcuts import render ,get_object_or_404
from bookcollection.models import Book,Author,Bookinstances,Genre,layout
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.contrib.auth.models import User ,Permission
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from bookcollection.forms import renewalbookform,issuessystemform
from django.urls import reverse
from django.http import HttpResponseRedirect
# Create your views here.

def index(request):
    book_request=Book.objects.all().count()
    author_request=Author.objects.all().count()
    book_copies=Bookinstances.objects.all().count()
    book_available=Bookinstances.objects.filter(status='a').count()
    image=layout.objects.all()
    print(image)
    context={
        'numbook':book_request,
        'numauthor':author_request,
        'numcopies':book_copies,
        'numavailable':book_available,
        'image':image,
    }

    return render(request,'bookcollection/home.html',context=context)


# using the class based generic list view  ListView


def booklist(request):
    book=Book.objects.all()
    context={'bookinfo':book}
    return render (request,'bookcollection/book.html',context=context)



def bookdetails(request,pk):
    
    try:
        book=Book.objects.get(pk=pk)
    
    except Book.DoesNotExist:
            raise Http404("Book-detail does not exist")

    
    return render(request,'bookcollection/book-detail.html',context={'book':book})


def author(request):
    authorinfo=Author.objects.all()
    context={'authorinfo':authorinfo}
    return render(request,'bookcollection/author.html',context=context)


def authordetail(request,pk):
    try:
        author=Author.objects.get(pk=pk)
    except Author.DoesNotExist:
        raise Http404('author-details does not exit')

    return render(request,'bookcollection/author-details.html',context={'authordetail':author})

'''
def loanbook(request):

    loan=Bookinstances.objects.filter(borrower=self.request.user).filter(status='o').order_by('due_back')
    return render(request,'bookcollection/loaned-book.html',context={'loanedbook':loan})
'''

class loanbook(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = Bookinstances
    template_name ='bookcollection/loaned-book.html'
    user=User.objects.all()
    print(user) 

    
    def get_context_data(self,**kwargs):
          context = super(loanbook, self).get_context_data(**kwargs)
          context['bookborrow']= Bookinstances.objects.filter(borrower=self.request.user).order_by('due_back')
          return context




''' 
    def get_queryset(self):
        print(self.request.user)
        print(Bookinstances.objects.filter(borrower=self.request.user).order_by('due_back'))
        return Bookinstances.objects.filter(borrower=self.request.user).order_by('due_back')

'''
# @permission_required('staff')
@permission_required('bookcollection.can_mark_returned')
def my_staff(request):
    
    users=User.objects.all()
    print(users)
    booklist=Bookinstances.objects.all()
    return render(request,'bookcollection/allbooks.html',context={'users':users,'booklist':booklist})    

# @permission_required('bookcollection.can_mark_returned')
# @permission_required('bookcollection.can_renew')
def renewsystem(request,pk):
    book_instance=get_object_or_404(Bookinstances,pk=pk)   
    print(book_instance)
    if request.method=='POST':  
        renewform=renewalbookform(request.POST)
        if renewform.is_valid():
            # safe the new date into the database
            book_instance.due_back=renewform.cleaned_data['renew']

            book_instance.save()
            return HttpResponseRedirect(reverse('allbooks'))


    else:
        
        suggested=datetime.date.today() + datetime.timedelta(weeks=3)
        # making new form
        renewform=renewalbookform(initial={'renew':suggested})
        
    context={
        'renewform':renewform,
        'book_instance':book_instance,
        }

    return render(request,'bookcollection/renewsystem.html',context)




def userrenewsystem(request,pk):
    book_instance=get_object_or_404(Bookinstances,pk=pk)   
    print(book_instance)
    if request.method=='POST':  
        renewform=renewalbookform(request.POST)
        if renewform.is_valid():
            # safe the new date into the database
            book_instance.due_back=renewform.cleaned_data['renew']
            print("useruser is gooing it")

            book_instance.save()
            return HttpResponseRedirect(reverse('borrowed'))

    else:
        
        suggested=datetime.date.today() + datetime.timedelta(weeks=3)
        # making new form
        renewform=renewalbookform(initial={'renew':suggested})
        
    context={
        'renewform':renewform,
        'book_instance':book_instance,
        }

    return render(request,'bookcollection/renewsystem.html',context)






def availale(request):
    book=Book.objects.all()
    context={'book':book}
    return render(request,'bookcollection/available.html',context=context)


def issuesystem(request,pk):
    bookinst=Bookinstances.objects.get(pk=pk)
    if request.method=='POST':
        renewform=issuessystemform(request.POST)
        if renewform.is_valid():
            bookinst.due_back=renewform.cleaned_data['due_date']
            bookinst.borrower=renewform.cleaned_data['borrower']
            bookinst.status='o'
            bookinst.save()
            return HttpResponseRedirect(reverse('allbooks'))

    
    else: 
        suggested=datetime.date.today() + datetime.timedelta(weeks=3)
        # making new form
        
        renewform=issuessystemform(initial={'due_date':suggested})

    context={
        'renewform':renewform,
        'bookinst':bookinst,
    }
    return render(request,'bookcollection/issuesystem.html',context=context)

bookcollection/templates/bookcollection/allbooks.html
{% extends "./base.html" %}

{% block content %}

<h2 style="padding-bottom:15px;">Books Status</h2>
<hr>

<ul class="home">
    {% for x in users %}
    {% for y in booklist %}
    {% if y.borrower == x %}
    
    <li><a href="{% url 'renew-system' y.pk %}">{{y.book1.title}}</a> ({{y.due_back}}): <strong><i>{{y.borrower}}</i></strong> </li>
    {% endif %}
    {% endfor %}
    {% endfor %}
</ul>
{% endblock %}

bookcollection/templates/bookcollection/author-details.html
{% extends './base.html'      %}

{% block content %}
<h2>About Author</h2> 
<hr>
{% if authordetail %}
<div>
    <p><strong>Name:</strong> {{authordetail.name}} </p>
    <p><strong>Birth-date:</strong>{{authordetail.dateofbith}}</p>
    <p><strong>Died:</strong>{{authordetail.dateofdeath}} </p>
</div>
{% endif %}

{% endblock %}

bookcollection/templates/bookcollection/author.html
{% extends './base.html' %}


{%  block content %}
<h2>Author Details</h2>

<hr>
<!-- 
<div>
    <ul class=home>
        {% for info in authorinfo  %}
        <div class=flex>

        <li class=list ><strong>Name:</strong> <a href="{{  info.get_absolute_url }} ">{{ info.name }} </a> </li>
        <!--- <p><strong>Birth-date:</strong>{{info.dateofbith }}</p>
        <p><strong>Died</strong>{{info.dateofdeath}}</p> -->
      
        <!-- <img class="selector"  src="{{info.image.url}}" alt="">      -->
        <!-- style="border-radius:50%;margin-left: 1200px; -->
        <!-- height="200px" width="143px" -->
        <!-- <hr>  -->
        <!-- </div> -->
        <!-- {% endfor %} -->
    <!-- </ul> -->
<!-- </div> --> 

<div class=flex >
    {% for info in authorinfo %}
    <a style="color:black" href="{{  info.get_absolute_url }} "> 
    <div class="card " style="width:18rem;margin:4em;">
        
        <img class="card-img-top" id="img-1" src="{{info.image.url}}" alt="Card image cap">
        <div class="card-body">
          <p class="card-text"> <strong> {{info.name}} </strong> </p>   
           <p class="card-text" >  {{info.dateofbith}}-{{info.dateofdeath}} </p>   
        
        </div>
      </div>
        </a>
      {% endfor %}
</div>


{% endblock %}

bookcollection/templates/bookcollection/available.html
{% extends "./base.html" %}


{% block content %}
<h2>Book Issuing</h2>
<hr>
{%for x in book%}
{% for y in x.bookinstances_set.all %}
{% if y.status  ==  'a' %}

<h4><strong> <a href="{% url 'issue' y.pk    %}"> Title:</strong>{{x.title}} </a> </h4>
{% endif %}
{% endfor %}

{%  endfor %}
{% endblock %}

bookcollection/templates/bookcollection/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}  <title>local library</title> {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/2.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Song+Myung" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans|Yanone+Kaffeesatz" rel="stylesheet">
</head>
<body>
    
    <div class=main>
        <img src="{% static 'images/books.png' %}"   >
        <h2 id='hding'>Book Stack</h2>
         
    </div>
<br>
    
    <div class="container-fluid">
       
            <div class= >
                {%block sidebar %}
                <ul class="navigation" id="myDIV" >
                    <li ><a href="{%url 'catalog' %}">Home</a></li>
                    <li><a href="{% url 'books' %}">ALL Books</a></li>
                    <li><a href="{% url 'author' %}">All Author</a></li>
                    {% if user.is_authenticated %}
                    
                   
                    {% if perms.bookcollection.can_mark_returned and  perms.bookcollection.staff %} 
                    <li ><a href="{% url 'allbooks' %}">Status</a></li>
                    <li><a href="{% url 'available' %}">Issue</a></li>
                    <li class=right><a href="" disabled="disabled" > <strong> User:</strong> <i>{{user}} </i> </a> </li>
                    <li><a class="active" href="{% url 'logout' %}">Logout</a></li>    
                    {% else %}
                    <li><a href="{% url 'borrowed' %}">Borrowed Books</a></li>
                    <li class="right"><a href="" disabled="disabled" > <strong> User:</strong> <i>{{user}} </i> </a> </li>
                    <li ><a class='active'   href="{% url 'logout'%}"> Logout </a></li> 
                    {% endif %}              
                    {% else %}
                    <li class="right"><a class="active" href="{% url 'login' %}"> Login</a></li>
                    {% endif %} 
                
                </ul>  

                {% endblock %}
                <!-- <script> -->
                        <!-- // Add active class to the current button (highlight it) -->
                        <!-- var header = document.getElementById("myDIV"); -->
                        <!-- var btns = header.getElementsByClassName("navigation li a"); -->
                        <!-- for (var i = 0; i < btns.length; i++) { -->
                          <!-- btns[i].addEventListener("click", function() { -->
                          <!-- var current = document.getElementsByClassName("active"); -->
                          <!-- current[0].className = current[0].className.replace(" active", ""); -->
                          <!-- this.className += " active"; -->
                          <!-- }); -->
                        <!-- } -->
                        <!-- </script> -->
            

            </div>

            <div> {% block content %}<!--  this is content -->{% endblock %}</div>
        

    
    </div>
</body>
</html> 

bookcollection/templates/bookcollection/book-detail.html
{% extends  "./base.html" %}

{% block content %}
<h2 style="padding-bottom:15px;text-align:left;" >Title: {{book.title }}</h2>
 
<!-- <p><strong>Author:</strong><a href="{% url 'author'  %}">{{book.author}}</a> </p> -->
<p><strong>ISBN:</strong>{{book.isbn}}</p>
<p><strong>Genre:</strong>{{book.genre.all|join:','}}</p>
<p><strong>Summary:</strong>{{book.summary}}</p>


<div style='margin-top:30px '>

</div>
<div>
<h4>copies</h4>
<hr>
{% for copy in book.bookinstances_set.all %}


{% if copy.status == 'a' %}
<p>Available</p>
{% elif copy.status == 'm' %}
<p>Maintained</p>
{% elif copy.status == 'o'  %}
<p>Onloan</p>
{% else %}
<p>Reserved</p>
{% endif %}
{% if copy.status == r %}
<p><strong>DueDate:{{copy.due_back}}</strong></p>
{% endif %}

<p><strong>Imprint-</strong>{{copy.imprint}}</p>
<p><strong>ID:</strong>{{copy.id}}</p>
{% endfor %}
</div>
{% endblock %}

   
            

bookcollection/templates/bookcollection/book.html
{% extends "./base.html" %}

{% block content  %}
<h2>Name of the books</h2>
<hr>

{% if bookinfo %}
<ul class=home  >
    {% for book in bookinfo %}
    <li><a href="{{ book.get_absolute_url }}">{{ book.title }} </a> {{book.author}}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No book is present</p>
{% endif %}
{% endblock %}

bookcollection/templates/bookcollection/home.html
{% extends "./base.html" %}

{% block content %}
{% load static %}
    <h1> Welcome  </h1>
    
    <p style="padding: 3px 0px;">Library has the following record</p>

    <div class="fix">



    <div class="card mb-3" id='style'  >
            <div class="row no-gutters">
              <div class="col-md-4" style="size: width ;">
                <img   src="{% static  'images/book-image.png'  %}" class="card-img" alt="..."  ">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <!-- <h5 class="card-title">Card title</h5> -->
                  
                 <h5 class="card-text" style="font-size:50px;"> {{numbook}} </h5>
                  <p class="card-text"> <b class=text-muted> Text Books! </b> </p>
                </div>
              </div>
            </div>
        </div>
    
        <br>
        <div class="card mb-3" id="style" >
            <div class="row no-gutters">
              <div class="col-md-4">
                <!-- <img src="..." class="card-img" alt="..."> -->
                <img src="{% static  'images/writter.png'  %}" class="card-img" alt="..."  ">

              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <!-- <h5 class="card-title">Card title</h5> -->
                  <h5 class="card-text" style="font-size:50px;"> {{numauthor}}</h5>
                  <p class="card-text"> <b class=text-muted>  Writer! </b> </p>
                </div>
              </div>
            </div>
          </div>
        <br>
        <div class="card mb-3" id='style' >
            <div class="row no-gutters">
              <div class="col-md-4">
                <!-- <img src="..." class="card-img" alt="..."> -->
                <img src="{% static  'images/2.png'  %}" class="card-img" alt="..."  ">

            </div>
              <div class="col-md-8">
                <div class="card-body">
                  <!-- <h5 class="card-title">Card title</h5> -->
                  <h5 class="card-text" style="font-size:50px" >{{numcopies}}</h5>
                  <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
                  <p class="card-text"> <b class=text-muted> Copies! </b> </p>
                </div>
              </div>
            </div>
          </div>
        <br>
        <div class="card mb-3" id="style" >
            <div class="row no-gutters">
              <div class="col-md-4">
                <!-- <img src="..." class="card-img" alt="..."> -->
                <img src="{% static  'images/available.png'  %}" class="card-img" alt="..."  ">

            </div>
              <div class="col-md-8">
                <div class="card-body">
                  <!-- <h5 class="card-title">Card title</h5> -->
                  <h5 class="card-text" style="font-size:50px" >{{numavailable}}</h5>
                  <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
                  <p class="card-text"> <b class=text-muted> Available! </b> </p>
                </div>
              </div>
            </div>
          </div>

          <br>
    
    </div>








{% endblock %}

bookcollection/templates/bookcollection/issuesystem.html
{% extends "./base.html" %}

{%block content%}

<h2 sytle="padding-bottom:10px" ><strong>Title:</strong>{{bookinst.book.title}}</h2>
<hr>


<h5 style="padding:10px 0px"><strong>  UUID: </strong>{{bookinst.id}} </h5>

<form action="" method="POST">
    {% csrf_token %}
    <table>
                
        {{renewform.as_table}}
    </table>
    <input type="submit" value="submit" >
</form>

{% endblock %}

bookcollection/templates/bookcollection/loaned-book.html
{% extends './base.html' %}

{% block content  %}

<h2>Borrowed Books</h2>
<hr>
<ul> {% if bookborrow %}

  {% for bookinst in bookborrow %} 
<li><a href="{% url 'book-detail' bookinst.book1.pk %}">{{bookinst.book1.title}}</a> ({{ bookinst.due_back }}) :   
  <b><a  href="{% url 'userrenewsystem' bookinst.pk %}">Renew</a> </b>     
  </li>
  {% endfor %}
</ul>
    {% else %}
  <p>There are no books borrowed.</p>
    {% endif %}
  {% endblock %}  

bookcollection/templates/bookcollection/renewsystem.html
{% extends "./base.html" %}
{% block content %}
<h2 style="padding-bottom:15px;">Please renew your book here</h2>
<hr>
<h5 style="padding-top:8px"> <b> Title:</b> {{ book_instance.book.title }}</h5>

<p>Borrower:{{book_instance.borrower}}</p>

<p>DueDate:{{book_instance.due_back}}</p>
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{renewform.as_table}}
    </table>
    <input type="submit" value='Submit'>
</form>
{% endblock %}